
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '8C34D412249559E0784F00079D956792'
    
_lr_action_items = {'PYCODE':([7,9,10,13,],[12,-10,-8,-7,]),'GIVES':([3,4,],[6,-9,]),'SYMBOL':([0,1,2,5,6,8,9,10,11,12,14,15,],[4,4,-2,-1,9,-3,-10,9,-5,-6,9,-4,]),'$end':([1,2,5,8,11,12,15,],[0,-2,-1,-3,-5,-6,-4,]),'OR':([11,12,],[14,-6,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'rules':([0,],[1,]),'rule':([0,1,],[2,5,]),'leftsymb':([0,1,],[3,3,]),'bodies':([6,14,],[8,15,]),'terminal':([6,10,14,],[10,10,10,]),'body':([6,14,],[11,11,]),'terminals':([6,10,14,],[7,13,7,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> rules","S'",1,None,None,None),
  ('rules -> rules rule','rules',2,'p_rules','parse.py',11),
  ('rules -> rule','rules',1,'p_rules','parse.py',12),
  ('rule -> leftsymb GIVES bodies','rule',3,'p_rule','parse.py',21),
  ('bodies -> body OR bodies','bodies',3,'p_bodies','parse.py',25),
  ('bodies -> body','bodies',1,'p_bodies','parse.py',26),
  ('body -> terminals PYCODE','body',2,'p_body','parse.py',33),
  ('terminals -> terminal terminals','terminals',2,'p_terminals','parse.py',37),
  ('terminals -> terminal','terminals',1,'p_terminals','parse.py',38),
  ('leftsymb -> SYMBOL','leftsymb',1,'p_leftsymb','parse.py',45),
  ('terminal -> SYMBOL','terminal',1,'p_terminal','parse.py',49),
]
